const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {createRequire}=require('node:module');const {DatabaseSync}=require('node:sqlite');
const {build}=createRequire(require.resolve('vite'))('esbuild');
const root=process.cwd();const RealDate=Date;let clock=RealDate.now();
global.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}};
const dateNow=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const tomorrow=s=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10);};
fs.mkdirSync('work',{recursive:true});fs.writeFileSync('work/test-env.ts','export const env = (globalThis as any).__bakeryTestEnv;');
const dbFile='work/api-verification.sqlite';if(fs.existsSync(dbFile))fs.unlinkSync(dbFile);let sql=new DatabaseSync(dbFile);
for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const adapter={prepare(query){const stmt={query,values:[],bind(...values){this.values=values;assert(values.length<=100,'D1 binding limit');return this;},async run(){const result=sql.prepare(this.query).run(...this.values);return {success:true,meta:{changes:Number(result.changes)}};},async all(){return {success:true,results:sql.prepare(this.query).all(...this.values)}}};return stmt;},async batch(statements){sql.exec('BEGIN');try{const r=statements.map(s=>/^\s*SELECT/i.test(s.query)?{success:true,results:sql.prepare(s.query).all(...s.values)}:{success:true,results:[],meta:{changes:Number(sql.prepare(s.query).run(...s.values).changes)}});sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
global.__bakeryTestEnv={DB:adapter,ASSETS:{async fetch(request){const p=path.join(root,'public',new URL(request.url).pathname);return fs.existsSync(p)?new Response(fs.readFileSync(p),{headers:{'Content-Type':'application/json'}}):new Response('Not found',{status:404});}}};
async function main(){
 await build({entryPoints:['app/api/bakery/route.ts'],outfile:'work/api-under-test.cjs',bundle:true,platform:'node',format:'cjs',alias:{'cloudflare:workers':path.join(root,'work/test-env.ts'),'@':root},logLevel:'silent'});
 const api=require('../work/api-under-test.cjs');let expectedErrors=0;const errorLog=console.error;console.error=()=>{expectedErrors++;};
 const post=async(action,payload={},space='real',expected=200)=>{const r=await api.POST(new Request('https://bakery.test/api/bakery',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://bakery.test'},body:JSON.stringify({space,action,...payload})}));const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return data;};
 const get=async(space='real')=>{const r=await api.GET(new Request('https://bakery.test/api/bakery?space='+space));assert.equal(r.status,200);return r.json();};
 assert.equal((await get()).records.length,0);
 const {product}=await post('product_save',{product:{name:'소금빵',batch:6,capacity:150}}),date=dateNow(),target=tomorrow(date);
 const record={productId:product.id,date,sales:72,produced:90,opening:0,closing:12,waste:6,carry:8,adjustment:0,stockout:false,temperature:23,rain:false,event:'',note:''};
 await post('record_save',{record});
 const preview=await post('plan_preview',{plan:{productId:product.id,target,inventory:8,reservations:20}});
 assert.equal(preview.forecast.mode,'fallback');assert.equal(preview.forecast.models.length,5);assert.equal(preview.forecast.models[0].quantity,66);
 const saved=await post('plan_commit',{plan:{productId:product.id,target,inventory:8,reservations:20},quantity:72});
 const frozen=JSON.stringify(saved.forecast);assert.equal(saved.plan.quantity,72);
 await post('plan_commit',{plan:{productId:product.id,target,inventory:0,reservations:999},quantity:150});
 assert.equal(JSON.stringify((await get()).forecasts[0]),frozen,'Forecast must not be overwritten');
 assert.equal((await get()).plans[0].quantity,72);
 await post('record_save',{record:{...record,sales:-1}},'real',400);
 await post('record_save',{record:{...record,carry:13}},'real',400);
 await post('record_save',{record:{...record,date:target}},'real',400);
 const csv='날짜,상품명,판매수량,품절\n'+date+',크루아상,20,\n';
 const ip=await post('import_preview',{csv});assert.equal(ip.count,1);assert.equal(ip.errorCount,0);
 assert.equal((await get()).records.length,1,'Preview must not persist');
 await post('import_commit',{csv});const imported=(await get()).records.find(r=>r.productId!==product.id);assert.equal(imported.stockout,null);assert.equal(imported.produced,null);
 const duplicate=await post('import_preview',{csv});assert.equal(duplicate.errorCount,1);
 await post('import_commit',{csv},'real',400);
 clock+=86400000;
 await post('record_save',{record:{...record,date:target,sales:68,opening:8,produced:72,closing:9,waste:3,carry:4}});
 let state=await get();const {metrics}=require('../work/test-cjs/metrics.js'),score=metrics(state.forecasts,state.records);
 assert.equal(score.n,1);assert.equal(score.rows[0].mae,4);assert.equal(score.rows[0].over,6);assert.equal(score.rows[0].loss,6);
 assert.equal(JSON.stringify(state.forecasts[0]),frozen);
 await post('plan_quantity',{id:saved.plan.id,quantity:78},'real',400);
 await post('record_save',{record:{...record,sales:70,closing:14}});
 assert.equal(JSON.stringify((await get()).forecasts[0]),frozen,'Corrected history must not rewrite forecasts');
 await post('demo_seed',{},'demo');const demo=await get('demo');assert(demo.records.length>=100);assert.equal((await get()).records.length,3,'Demo must not touch store records');
 sql.close();sql=new DatabaseSync(dbFile);state=await get();assert.equal(state.records.length,3,'Records survive database reopen');assert.equal(JSON.stringify(state.forecasts[0]),frozen);
 const denied=await api.POST(new Request('https://bakery.test/api/bakery',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://elsewhere.test'},body:'{}'}));assert.equal(denied.status,403);
 console.error=errorLog;sql.close();
 const report={apiHandlers:'passed',sqliteMigration:'passed',persistentReopen:'passed',dailyNextDayComparison:'passed',immutableForecasts:'passed',importPreviewAndValidation:'passed',unknownStockoutPreserved:'passed',demoIsolation:'passed',invalidQuantitiesAndDates:'passed',crossOriginWritesRejected:true,backend:'actual API handlers against SQLite D1 adapter; browser and hosted D1 not exercised'};
 fs.writeFileSync('research/api-verification.json',JSON.stringify(report,null,2));console.log(report);
}
main().catch(e=>{console.error(e);process.exitCode=1;});
