import {z} from "zod";
import {localDate,type DayRecord,type Product} from "./bakery-types";
const count=z.number().int().min(0).max(100000);
const optional=count.nullable().optional().default(null);
export const dateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>{try{return new Date(s+"T12:00:00Z").toISOString().slice(0,10)===s;}catch{return false;}},"올바른 날짜를 입력해 주세요.");
export const productSchema=z.object({id:z.string().max(120).optional(),name:z.string().trim().min(1,"상품명을 입력해 주세요.").max(60),batch:z.number().int().min(1).max(1000),capacity:optional,active:z.boolean().default(true)});
export const recordSchema=z.object({productId:z.string().min(1).max(120),date:dateSchema,sales:count,opening:optional,produced:optional,closing:optional,waste:optional,carry:optional,adjustment:z.number().int().min(-100000).max(100000).default(0),stockout:z.boolean().nullable().default(null),temperature:z.number().min(-60).max(60).nullable().optional().default(null),rain:z.boolean().default(false),event:z.string().max(100).default(""),note:z.string().max(1000).default("")});
export function parseRecord(data:unknown){const r=recordSchema.parse(data);if(r.date>localDate())throw new Error("미래 날짜의 실제 판매를 기록할 수 없습니다.");if(r.carry!==null&&r.closing!==null&&r.carry>r.closing)throw new Error("판매 가능한 이월재고는 실제 마감 재고보다 많을 수 없습니다.");return r;}
export function balanceDifference(r:Pick<DayRecord,"opening"|"produced"|"adjustment"|"sales"|"waste"|"closing">){if(r.opening===null||r.produced===null||r.waste===null||r.closing===null)return null;return r.closing-(r.opening+r.produced+r.adjustment-r.sales-r.waste);}
export const planSchema=z.object({productId:z.string().min(1).max(120),target:dateSchema,inventory:count,reservations:count});
export function validateManualQuantity(quantity:unknown,product:Pick<Product,"batch"|"capacity">){const q=count.parse(quantity);if(q%product.batch!==0)throw new Error(`생산 단위 ${product.batch}개에 맞춰 입력해 주세요.`);if(product.capacity!==null&&q>product.capacity)throw new Error("설정한 최대 생산량을 초과했습니다. 상품 설정을 확인해 주세요.");return q;}
export function errorMessage(error:unknown){if(error instanceof z.ZodError){const item=error.issues[0],key=String(item.path.at(-1)??"");const labels:Record<string,string>={sales:"판매량",produced:"생산량",opening:"시작 재고",closing:"마감 재고",waste:"폐기량",carry:"이월재고",inventory:"판매 가능한 재고",reservations:"예약",batch:"생산 단위",capacity:"최대 생산량",name:"상품명",date:"날짜",target:"예측 날짜",temperature:"기온"};return `${labels[key]??"입력값"}을 확인해 주세요. ${["sales","produced","opening","closing","waste","carry","inventory","reservations","capacity"].includes(key)?"수량은 0 이상 100,000 이하의 정수로 입력합니다.":key==="batch"?"생산 단위는 1 이상 1,000 이하입니다.":item.code==="custom"?item.message:"필수 항목과 숫자 범위를 확인해 주세요."}`;}return error instanceof Error?error.message:"요청을 완료하지 못했습니다. 다시 시도해 주세요.";}
